---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vite-react
  template:
    metadata:
      labels:
        app: vite-react
    spec:
      containers:
      - name: vite-react
        image: satvik004/vite-react-app:latest
        ports:
        - containerPort: 80

